### PR TITLE
behavior better separated from tax law params

### PR DESCRIPTION
**Pull request by PeterDSteinberg**
1) moved behavior input parameters from params.json to behavior.json
2) added a Behavior class in behavior.py that has implement_reform, set_year, current_year and other attributes similar to the tax law parameters class Parameters.
3) added a behavior=None argument to Calculator
4) in Calculator made increment_year do the set_year method of self.behavior and self.params
5) updated the behavior test based on new syntax
6) updated the ipython notebook Behavioral_example.ipynb

### CODE REVIEW

**Comment by MattHJensen** [comment]
Thanks @PeterDSteinberg 

The aspect of this approach that makes me nervous is that we have a lot of duplicated functionality between `Behavior` and `Parameters`. 

It seems the logical extension for @amy-xu's work https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/368 would be to have another Growth class, in which case we will have duplicated functionality between Behavior, Parameters, and Growth. 

@martinholmer, what do you think about this? 

Really there are two questions:

1. Does it seem like a good long-term path to create new classes for every new type of parameter we have, even if we handle the parameters in very similar ways?
2. If the answer is no, then what is the best way to proceed given our desire to quickly add these new features:
    * create the new classes as in this PR and then refactor later. 
    * go ahead and add things to params.json as in https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/368 and https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/367 and refactor later. 
    * Follow some other path that could be executed on quickly. 

One option might be to keep tax law params, behavioral params, and growth params as subclasses of Parameters and separate JSONs for each. If this couldn't be executed quickly, then we could have this be the 'refactor later' part of the first two bullets. 

cc @talumbau

**Comment by PeterDSteinberg** [comment]
@MattHJensen: Regarding item 1) above, one idea may be to just factor out some of the methods of Parameters into standalone functions and that may leave separate class implementations less complicated.
cc @talumbau

**Comment by martinholmer** [comment]
@MattHJensen said:
> The aspect of this approach that makes me nervous is that we have a lot of duplicated functionality between Behavior and Parameters.
>
> It seems the logical extension for @amy-xu's work OpenSourcePolicyCenter#368 would be to have another Growth class, in which case we will have duplicated functionality between Behavior, Parameters, and Growth.
>
> @martinholmer, what do you think about this?

@MattHJensen,  @PeterDSteinberg, @Amy-Xu,

After only a very brief look at the preliminary code, it seems as if much of the duplicated functionality is unnecessary for the Behavior class.  For example, why does behavior.json have a cpi_indexed key?  Would that ever be necessary?  Seem like all the Behavior class needs to do is read in the behavioral assumptions, extend them to all the budget years (if they are not explicitly specified and there is a utility for doing this), and set the values for the current year.  How much duplication of code can that involve?  Or am I missing the need for other Behavior functionality?  If I'm not missing something, it seems the main problem is that the copy and paste of the Parameters code has not been followed up with enough simplification and customization to suit tax reform behavioral assumptions.

But the __biggest problem__ that I see in the preliminary code for the Behavior class is that there is no easy way for a user to say: "I want to do my tax analysis without any behavioral responses".  Because this is such a common sort of analysis, a user should be able to do this without creating a custom behavior.json file with all zeros.  Shouldn't the Behavior class constructor have a parameter that indicates use of the no-behavioral-response assumptions?  If you make it difficult to use no behavioral responses, I'm afraid that some may accuse the OSPC of "forcing a particular set of dynamic scoring assumptions on the user" or some other criticism in the same vein.

**Comment by MattHJensen** [comment]
>But the biggest problem that I see in the preliminary code for the Behavior class is that there is no easy way for a user to say: "I want to do my tax analysis without any behavioral responses". Because this is such a common sort of analysis, a user should be able to do this without creating a custom behavior.json file with all zeros. Shouldn't the Behavior class constructor have a parameter that indicates use of the no-behavioral-response assumptions? If you make it difficult to use no behavioral responses, I'm afraid that some may accuse the OSPC of "forcing a particular set of dynamic scoring assumptions on the user" or some other criticism in the same vein.

@martinholmer, I don't think anyone can claim that OSPC is "forcing a particular set of dynamic scoring assumptions on the user" when the defaults are zeroes. In fact, I might argue that there is no such thing as having "no-behavioral-response-assumptions"; you can assume that there is no behavioral response, but that is still an assumption, namely that the values are zeroes.

**Comment by MattHJensen** [comment]
> After only a very brief look at the preliminary code, it seems as if much of the duplicated functionality is unnecessary for the Behavior class. For example, why does behavior.json have a cpi_indexed key? Would that ever be necessary? 

Agreed, the Behavior class doesn't need cpi inflation. But I can't think of much else from the Parameters class that it doesn't need. 

A user might want to compare a calculator with behavioral effects to a calculator without behavioral effects. This is analogous to comparing a calculator with one set of policy parameters to a calculator with another set of policy parameters. 

A user might want to assume that behavioral effects are different in different years. 

A user might want to specify behavioral effects for a few years and have it be assumed that they are extended thereafter. 

Some behavioral assumptions might have multiple dimensions; for example elasticity of taxable income might vary according to income level or the household wagesplit.

**Comment by martinholmer** [comment]
On Thu, Oct 1, 2015 at 7:53 AM, Matt Jensen <notifications@github.com>
wrote:

> But the biggest problem that I see in the preliminary code for the
> Behavior class is that there is no easy way for a user to say: "I want to
> do my tax analysis without any behavioral responses". Because this is such
> a common sort of analysis, a user should be able to do this without
> creating a custom behavior.json file with all zeros. Shouldn't the Behavior
> class constructor have a parameter that indicates use of the
> no-behavioral-response assumptions? If you make it difficult to use no
> behavioral responses, I'm afraid that some may accuse the OSPC of "forcing
> a particular set of dynamic scoring assumptions on the user" or some other
> criticism in the same vein.
>
> @martinholmer <https://github.com/martinholmer>, I don't think anyone can
> claim that OSPC is "forcing a particular set of dynamic scoring assumptions
> on the user" when the defaults are zeroes. In fact, I might argue that
> there is no such thing as having "no-behavioral-response-assumptions"; you
> can assume that there is no behavioral response, but that is still an
> assumption, namely that the values are zeroes.
>

@MattHJensen,

So you are saying that the behavior.json file has no behavioral responses
(that is, I guess, zeros for all the response parameters)?  If so, then my
concern was misplaced.

**Comment by MattHJensen** [comment]
>So you are saying that the behavior.json file has no behavioral responses
(that is, I guess, zeros for all the response parameters)? 

Yes, the plan is to have everything default to zero. Part of this is to prevent concerns like yours, part of this is to save the computation (we check if the behavioral params are zero before calculating marginal tax rates).

**Comment by martinholmer** [comment]
@MattHJensen, Sounds sensible.

**Comment by MattHJensen** [comment]
@martinholmer, do you have feedback on this: 

>Agreed, the Behavior class doesn't need cpi inflation. But I can't think of much else from the Parameters class that it doesn't need.

from https://github.com/MattHJensen/taxcalc/pull/5#issuecomment-144711839

**Comment by martinholmer** [comment]
@MattHJensen,
> @martinholmer, do you have feedback on this:

>> Agreed, the Behavior class doesn't need cpi inflation. But I can't think of much else from the Parameters class that it doesn't need.

> from #5 (comment)

I'm not sure how best to manage the fact that the model is getting more complex.  But that was bound to happen as you implement your original vision.

The way I think about the problem you're grappling with is based on my experience with PENSIM, which has thousands of parameters that characterize a wide variety of objects.  Despite the large number of input parameters, PENSIM has a single input file.  This simplification at the file level is accomplished because the file is an SQLite relational database file that contains about 300 different tables.  The logistics of  opening the database and reading parameters from a table are handled by utility functions, which reduces code duplication.  But there is a class for each type of object (which typically corresponds to several database tables) and the validity checking of user-supplied parameter values is done in each class.

You could consider making the params.json file look like a database file by specifying sub dictionaries:
the current policy parameters could be embedded in a "policy": { ... } sub dictionary, and the behavior parameters could be in a "behavior": { ... } sub directory, etc.  But there are clearly some cons to this approach.  And while is reduces the number of input parameter files, it does nothing to reduce code duplication.

The other thing you could consider is to continue developing the Behavior class in the behavior.py file, pare it down to the essentials, get it working, and then add tests that check its operation.  Then we can look for ways to eliminate code duplication --- identifying common logic and moving that logic to the utils.py file.  It is very difficult to do that now given that the Behavior class is still being developed and has not yet been tested.

Are there other near-term courses of action that might be better?

**Comment by MattHJensen** [comment]
Thank you @martinholmer, that is extremely helpful. 

> You could consider making the params.json file look like a database file by specifying sub dictionaries:
the current policy parameters could be embedded in a "policy": { ... } sub dictionary, and the behavior parameters could be in a "behavior": { ... } sub directory, etc. But there are clearly some cons to this approach. And while is reduces the number of input parameter files, it does nothing to reduce code duplication. 

Yes, seems like code duplication is a greater concern than the number of input files at this point. 

@PeterDSteinberg's suggestion

> @MattHJensen: Regarding item 1) above, one idea may be to just factor out some of the methods of Parameters into standalone functions and that may leave separate class implementations less complicated.
cc @talumbau

and @martinholmer's suggestion

> The other thing you could consider is to continue developing the Behavior class in the behavior.py file, pare it down to the essentials, get it working, and then add tests that check its operation. Then we can look for ways to eliminate code duplication --- identifying common logic and moving that logic to the utils.py file.

Seem to be quite similar. @PeterDSteinberg, if you yank out CPI inflation and anything else you don't think we need then I will merge this and we can move back to the PR on the taxcalc repo.

**Comment by PeterDSteinberg** [comment]
sounds good @MattHJensen .  I will make that cpi change and also simplify away some of the similarity between between Parameters and Behavior.

**Comment by MattHJensen** [comment]
>and also simplify away some of the similarity between between Parameters and Behavior. 

Do you think it makes sense to do this as a separate PR once the Behavior class is merged to master? I'm hoping that refactor doesn't block getting Behavior into master.

**Comment by PeterDSteinberg** [comment]
Sure @MattHJensen separate PR sounds fine.

**Comment by martinholmer** [comment]
@MattHJensen and @PeterDSteinberg,

> Do you think it makes sense to do this as a separate PR once the Behavior class is merged to master? I'm hoping that refactor doesn't block getting Behavior into master.

I also agree that this is a sensible approach.

**Pull request merged**
